apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sock-shop-
  namespace: litmus
  labels:
    subject: sock-shop_litmus
spec:
  entrypoint: argowf-chaos
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
      - name: appNamespace
        value: sock-shop
  serviceAccountName: argo-chaos
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
  templates:
    - name: argowf-chaos
      steps:
        - - name: install-application
            template: install-application
        - - name: install-chaos-experiments
            template: install-chaos-experiments
          - name: load-test
            template: load-test
        - - name: pod-cpu-hog
            template: pod-cpu-hog
        - - name: pod-delete
            template: pod-delete
        - - name: pod-network-loss
            template: pod-network-loss
        - - name: pod-memory-hog
            template: pod-memory-hog
        - - name: disk-fill
            template: disk-fill
        - - name: revert-chaos
            template: revert-chaos
          - name: delete-loadtest
            template: delete-loadtest
    - name: install-application
      container:
        image: litmuschaos/litmus-app-deployer:latest
        args:
          - -namespace=sock-shop
          - -typeName=resilient
          - -operation=apply
          - -timeout=400
          - -app=sock-shop
          - -scope=cluster
    - name: install-chaos-experiments
      container:
        image: litmuschaos/k8s:latest
        command:
          - sh
          - -c
        args:
          - kubectl apply -f
            https://hub.litmuschaos.io/api/chaos/master?file=charts/generic/experiments.yaml
            -n {{workflow.parameters.adminModeNamespace}} ; sleep 30
    - name: pod-cpu-hog
      inputs:
        artifacts:
          - name: pod-cpu-hog
            path: /tmp/chaosengine.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                kind: ChaosEngine

                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  labels:
                    instance_id: f9118f53-6e71-4e6c-926c-f133977e0f78
                    workflow_name: sock-shop-1645447262
                  generateName: pod-cpu-hog-chaos
                spec:
                  appinfo:
                    appns: sock-shop
                    applabel: name=carts
                    appkind: deployment
                  jobCleanUpPolicy: retain
                  engineState: active
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: pod-cpu-hog
                      spec:
                        probe:
                          - name: check-frontend-access-url
                            type: httpProbe
                            httpProbe/inputs:
                              url: http://front-end.sock-shop.svc.cluster.local:80
                              insecureSkipVerify: false
                              responseTimeout: 100
                              method:
                                get:
                                  criteria: ==
                                  responseCode: "200"
                            mode: Continuous
                            runProperties:
                              probeTimeout: 2
                              interval: 1
                              retry: 2
                              probePollingInterval: 1
                          - name: check-benchmark
                            type: cmdProbe
                            cmdProbe/inputs:
                              command: curl http://qps-test.sock-shop.svc.cluster.local
                              comparator:
                                type: int
                                criteria: ">="
                                value: "100"
                            mode: Edge
                            runProperties:
                              probeTimeout: 2
                              interval: 1
                              retry: 2
                              initialDelaySeconds: 10
                        components:
                          env:
                            - name: CPU_CORES
                              value: "1"
                            - name: TOTAL_CHAOS_DURATION
                              value: "30"
                            - name: CHAOS_KILL_COMMAND
                              value: >-
                                kill -9 $(ps afx | grep "[md5sum] /dev/zero" | awk '{print$1}' |
                                tr '

                                ' ' ')
      metadata:
        labels:
          weight: "10"
      container:
        image: litmuschaos/litmus-checker:latest
        args:
          - -file=/tmp/chaosengine.yaml
          - -saveName=/tmp/engine-name
    - name: pod-memory-hog
      inputs:
        artifacts:
          - name: pod-memory-hog
            path: /tmp/chaosengine.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                kind: ChaosEngine

                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  labels:
                    instance_id: 5e8ae855-7a04-4577-8092-efa557948219
                    workflow_name: sock-shop-1645447262
                  generateName: pod-memory-hog-chaos
                spec:
                  appinfo:
                    appns: sock-shop
                    applabel: name=orders
                    appkind: deployment
                  jobCleanUpPolicy: retain
                  engineState: active
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: pod-memory-hog
                      spec:
                        probe:
                          - name: check-frontend-access-url
                            type: httpProbe
                            httpProbe/inputs:
                              url: http://front-end.sock-shop.svc.cluster.local:80
                              insecureSkipVerify: false
                              responseTimeout: 100
                              method:
                                get:
                                  criteria: ==
                                  responseCode: "200"
                            mode: Continuous
                            runProperties:
                              probeTimeout: 2
                              interval: 1
                              retry: 2
                              probePollingInterval: 1
                          - name: check-benchmark
                            type: cmdProbe
                            cmdProbe/inputs:
                              command: curl http://qps-test.sock-shop.svc.cluster.local
                              comparator:
                                type: int
                                criteria: ">="
                                value: "100"
                            mode: Edge
                            runProperties:
                              probeTimeout: 2
                              interval: 1
                              retry: 2
                              initialDelaySeconds: 10
                        components:
                          env:
                            - name: MEMORY_CONSUMPTION
                              value: "500"
                            - name: TOTAL_CHAOS_DURATION
                              value: "30"
                            - name: CHAOS_KILL_COMMAND
                              value: >-
                                kill -9 $(ps afx | grep "[dd] if /dev/zero" | awk '{print $1}' |
                                tr '

                                ' ' ')
      metadata:
        labels:
          weight: "10"
      container:
        image: litmuschaos/litmus-checker:latest
        args:
          - -file=/tmp/chaosengine.yaml
          - -saveName=/tmp/engine-name
    - name: pod-delete
      inputs:
        artifacts:
          - name: pod-delete
            path: /tmp/chaosengine.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                kind: ChaosEngine

                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  labels:
                    instance_id: b9562171-c1fa-4aea-9a91-a02c92b95d0c
                    workflow_name: sock-shop-1645447262
                  generateName: catalogue-pod-delete-chaos
                spec:
                  appinfo:
                    appns: sock-shop
                    applabel: name=catalogue
                    appkind: deployment
                  engineState: active
                  chaosServiceAccount: litmus-admin
                  jobCleanUpPolicy: retain
                  components:
                    runner:
                      imagePullPolicy: Always
                  experiments:
                    - name: pod-delete
                      spec:
                        probe:
                          - name: check-catalogue-access-url
                            type: httpProbe
                            httpProbe/inputs:
                              url: http://front-end.sock-shop.svc.cluster.local:80/catalogue
                              insecureSkipVerify: false
                              responseTimeout: 100
                              method:
                                get:
                                  criteria: ==
                                  responseCode: "200"
                            mode: Continuous
                            runProperties:
                              probeTimeout: 12
                              interval: 12
                              retry: 3
                              probePollingInterval: 1
                          - name: check-benchmark
                            type: cmdProbe
                            cmdProbe/inputs:
                              command: curl http://qps-test.sock-shop.svc.cluster.local
                              comparator:
                                type: int
                                criteria: ">="
                                value: "100"
                            mode: Edge
                            runProperties:
                              probeTimeout: 2
                              interval: 1
                              retry: 2
                              initialDelaySeconds: 2
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "30"
                            - name: CHAOS_INTERVAL
                              value: "10"
                            - name: FORCE
                              value: "false"
      metadata:
        labels:
          weight: "10"
      container:
        image: litmuschaos/litmus-checker:latest
        args:
          - -file=/tmp/chaosengine.yaml
          - -saveName=/tmp/engine-name
    - name: pod-network-loss
      inputs:
        artifacts:
          - name: pod-network-loss
            path: /tmp/chaosengine.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                kind: ChaosEngine

                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  labels:
                    instance_id: 0d0c422c-d868-47e9-9406-7b4401499d22
                    workflow_name: sock-shop-1645447262
                  generateName: pod-network-loss-chaos
                spec:
                  appinfo:
                    appns: sock-shop
                    applabel: name=user-db
                    appkind: statefulset
                  jobCleanUpPolicy: retain
                  engineState: active
                  chaosServiceAccount: litmus-admin
                  components:
                    runner:
                      imagePullPolicy: Always
                  experiments:
                    - name: pod-network-loss
                      spec:
                        probe:
                          - name: check-cards-access-url
                            type: httpProbe
                            httpProbe/inputs:
                              url: http://front-end.sock-shop.svc.cluster.local:80/cards
                              insecureSkipVerify: false
                              responseTimeout: 100
                              method:
                                get:
                                  criteria: ==
                                  responseCode: "200"
                            mode: Continuous
                            runProperties:
                              probeTimeout: 12
                              interval: 12
                              retry: 3
                              probePollingInterval: 1
                          - name: check-benchmark
                            type: cmdProbe
                            cmdProbe/inputs:
                              command: curl http://qps-test.sock-shop.svc.cluster.local
                              comparator:
                                type: int
                                criteria: ">="
                                value: "100"
                            mode: Edge
                            runProperties:
                              probeTimeout: 2
                              interval: 1
                              retry: 2
                              initialDelaySeconds: 2
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "30"
                            - name: NETWORK_INTERFACE
                              value: eth0
                            - name: NETWORK_PACKET_LOSS_PERCENTAGE
                              value: "100"
                            - name: CONTAINER_RUNTIME
                              value: docker
                            - name: SOCKET_PATH
                              value: /var/run/docker.sock
      metadata:
        labels:
          weight: "10"
      container:
        image: litmuschaos/litmus-checker:latest
        args:
          - -file=/tmp/chaosengine.yaml
          - -saveName=/tmp/engine-name
    - name: disk-fill
      inputs:
        artifacts:
          - name: disk-fill
            path: /tmp/chaosengine.yaml
            raw:
              data: >
                apiVersion: litmuschaos.io/v1alpha1

                kind: ChaosEngine

                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  labels:
                    instance_id: 783c85d1-7b83-46cb-a66d-83540b643b3c
                    workflow_name: sock-shop-1645447262
                  generateName: catalogue-disk-fill
                spec:
                  appinfo:
                    appns: sock-shop
                    applabel: name=catalogue-db
                    appkind: statefulset
                  engineState: active
                  chaosServiceAccount: litmus-admin
                  jobCleanUpPolicy: retain
                  components:
                    runner:
                      imagePullPolicy: Always
                  experiments:
                    - name: disk-fill
                      spec:
                        probe:
                          - name: check-catalogue-db-cr-status
                            type: k8sProbe
                            k8sProbe/inputs:
                              group: ""
                              version: v1
                              resource: pods
                              namespace: sock-shop
                              fieldSelector: status.phase=Running
                              labelSelector: name=catalogue-db
                              operation: present
                            mode: Continuous
                            runProperties:
                              probeTimeout: 1
                              interval: 1
                              retry: 1
                              probePollingInterval: 1
                          - name: check-benchmark
                            type: cmdProbe
                            cmdProbe/inputs:
                              command: curl http://qps-test.sock-shop.svc.cluster.local:80
                              comparator:
                                type: int
                                criteria: ">="
                                value: "100"
                            mode: Edge
                            runProperties:
                              probeTimeout: 2
                              interval: 1
                              retry: 2
                              initialDelaySeconds: 1
                        components:
                          env:
                            - name: FILL_PERCENTAGE
                              value: "100"
                            - name: TARGET_CONTAINER
                              value: ""
                            - name: TOTAL_CHAOS_DURATION
                              value: "30"
      metadata:
        labels:
          weight: "10"
      container:
        image: litmuschaos/litmus-checker:latest
        args:
          - -file=/tmp/chaosengine.yaml
          - -saveName=/tmp/engine-name
    - name: delete-application
      container:
        image: litmuschaos/litmus-app-deployer:latest
        args:
          - -namespace=sock-shop
          - -typeName=resilient
          - -operation=delete
          - -app=sock-shop
    - name: load-test
      container:
        image: litmuschaos/litmus-app-deployer:latest
        args:
          - -namespace=loadtest
          - -app=loadtest
    - name: delete-loadtest
      container:
        image: litmuschaos/litmus-app-deployer:latest
        args:
          - -namespace=loadtest
          - -operation=delete
          - -app=loadtest
    - name: revert-chaos
      container:
        image: litmuschaos/k8s:latest
        command:
          - sh
          - -c
        args:
          [
            "kubectl delete chaosengine pod-memory-hog-chaos pod-cpu-hog-chaos catalogue-pod-delete-chaos pod-network-loss-chaos -n {{workflow.parameters.adminModeNamespace}}",
          ]
