name: Chaos test
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
jobs:
  Tests:
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: /home/runner/.kube/config 

    steps:
      - name: Installing KinD cluster for the test
        run: kind create cluster

      - name: Configuring and testing the Installation
        run: |
          kubectl wait node --all --for condition=ready --timeout=120s
          kubectl get nodes 

      - name: Print cluster information
        run: |
          set -x
          kubectl cluster-info --context kind-kind
          kubectl get pods -n kube-system
          
          
      - name: Setup Litmus
        run: |
          set -x
          kubectl apply -f https://litmuschaos.github.io/litmus/litmus-operator-latest.yaml -n litmus
          kubectl wait --for=condition=Ready pods --all -n litmus --timeout=120s
          
      - name: Setup ArgoWorkflow
        run: |
          set -x
          kubectl create ns argo
          kubectl apply -f https://raw.githubusercontent.com/argoproj/argo/stable/manifests/install.yaml -n argo
          kubectl wait --for=condition=Available deployment workflow-controller -n argo --timeout=120s
          
      - name: Create the Argo Access ServiceAccount          
        run: |
          set -x
          kubectl apply -f https://raw.githubusercontent.com/litmuschaos/chaos-workflows/master/Argo/argo-access.yaml -n litmus
          
      - name: Configure Argo to work in kind
        run: | 
          # kind’s cluster does not use Docker, which is the default container runtime used by Argo’s Workflow controller. 
          # Instead Kind uses containerd. 
          # Fortunately, Argo’s Workflow Controller may be configured. 
          # Argo documents the configuration pretty well in their workflow-controller-configmap docs.
          #
          # https://argoproj.github.io/argo-workflows/workflow-executors/
          # https://github.com/argoproj/argo-workflows/blob/v2.11.8/docs/workflow-controller-configmap.yaml#L95
          #
          set -x
          kubectl patch configmap workflow-controller-configmap -n argo --patch '{"data": {"containerRuntimeExecutor": "pns"}}' --type merge
          
      - name: Install Argo CLI
        run: |           
          set -x
          curl https://github.com/argoproj/argo-workflows/releases/download/v3.2.8/argo-linux-amd64.gz --location --output ~/argo.gz
          gunzip ~/argo.gz
          chmod +x ~/argo
          ~/argo version
          
      - name: Run Argo Workflow
        run: |           
          set -x
          ~/argo submit https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/workflows/sock-shop/workflow.yaml -n litmus --log
          
