name: Debuging Action
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'debug'
        
jobs:
  test:
    runs-on: ubuntu-latest
    steps:  
      - name: Set ginkgo parameters
        run: |
            echo 'GINKGO_PARAMETERS="--ginkgo.v"' >> "$GITHUB_ENV
            
            if [[ "pull_request" == "push" ]] || \
               [[ "pull_request" == "pull_request" ]] || \
               [[ "" == "feature" ]]; then
              echo 'GINKGO_PARAMETERS=${GINKGO_PARAMETERS} --ginkgo.skip="\[Chaos\]"' >> "$GITHUB_ENV"
            elif [[ "" == "chaos" ]]; then
              echo 'GINKGO_PARAMETERS=${GINKGO_PARAMETERS} --ginkgo.focus="\[Chaos\]"' >> "$GITHUB_ENV"
            fi
      - name: test
        run: |
          set -x
          ginkgo -p ./test/e2e -- \
            ${GINKGO_PARAMETERS}  
