name: Test

on:
  workflow_dispatch:

jobs:
  run_experiments:
    name: Run experiments
    runs-on: ubuntu-latest
    
    steps:
      - name: Installing Prerequisites (KinD Cluster)
        uses: engineerd/setup-kind@v0.5.0
        with:
            version: "v0.7.0"

      - name: Configuring and testing the Installation
        run: |
          kubectl cluster-info --context kind-kind
          kind get kubeconfig --internal >$HOME/.kube/config
          kubectl get nodes
      - name: Deploy a sample application for chaos injection
        run: |
          kubectl apply -f https://raw.githubusercontent.com/litmuschaos/chaos-ci-lib/master/app/nginx.yml
          kubectl wait --for=condition=Ready pods --all --namespace default --timeout=60s
          
      - name: Setting up kubeconfig ENV for Github Chaos Action
        run: echo ::set-env name=KUBE_CONFIG_DATA::$(base64 -w 0 ~/.kube/config)
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Setup Litmus
        uses: litmuschaos/github-chaos-actions@master
        env:
          INSTALL_LITMUS: true    

      # Pod Delete
      - name: Running Litmus pod delete chaos experiment
        uses: litmuschaos/github-chaos-actions@master
        env:
          EXPERIMENT_NAME: pod-delete
          EXPERIMENT_IMAGE: litmuschaos/go-runner
      
      
                  
      # Container Kill
      - name: Running container kill chaos experiment
        uses: litmuschaos/github-chaos-actions@master
        env:
          EXPERIMENT_NAME: container-kill
          EXPERIMENT_IMAGE: litmuschaos/go-runner
      
      # Pod CPU Hog
      - name: Running pod-cpu-hog chaos experiment
        uses: litmuschaos/github-chaos-actions@master
        env:
          EXPERIMENT_NAME: pod-cpu-hog
          EXPERIMENT_IMAGE: litmuschaos/go-runner
      
      # Pod Network Corruption
      - name: Running pod network corruption chaos experiment
        uses: litmuschaos/github-chaos-actions@master
        env:
          EXPERIMENT_NAME: pod-network-corruption
          EXPERIMENT_IMAGE: litmuschaos/go-runner


      # Pod Network Duplication
      - name: Running pod network duplication chaos experiment
        uses: litmuschaos/github-chaos-actions@master
        env:       
          EXPERIMENT_NAME: pod-network-duplication
          EXPERIMENT_IMAGE: litmuschaos/go-runner
        

      # Pod Network Latency
      - name: Running pod-network-latency chaos experiment
        uses: litmuschaos/github-chaos-actions@master
        env: 
          EXPERIMENT_NAME: pod-network-latency
          EXPERIMENT_IMAGE: litmuschaos/go-runner
          
      # Pod Network Loss
      - name: Running pod-network-loss chaos experiment
        uses: litmuschaos/github-chaos-actions@master
        env:
          EXPERIMENT_NAME: pod-network-loss
          EXPERIMENT_IMAGE: litmuschaos/go-runner
          
      # Node CPU Hog
      - name: Running node-cpu-hog chaos experiment
        uses: litmuschaos/github-chaos-actions@master
        env:
          EXPERIMENT_NAME: node-cpu-hog
          EXPERIMENT_IMAGE: litmuschaos/go-runner
          
      # Node Node Memory Hog
      - name: Running node-memory-hog chaos experiment
        uses: litmuschaos/github-chaos-actions@master
        env:
          EXPERIMENT_NAME: node-memory-hog
          EXPERIMENT_IMAGE: litmuschaos/go-runner
          
      # Node IO Stress
      - name: Running node-io-stress chaos experiment
        uses: litmuschaos/github-chaos-actions@master
        env:
          EXPERIMENT_NAME: node-io-stress
          EXPERIMENT_IMAGE: litmuschaos/go-runner
          

      - name: Uninstall Litmus
        uses: litmuschaos/github-chaos-actions@master
        env:          
          LITMUS_CLEANUP: true

      - name: Deleting KinD cluster
        if: ${{ always() }}
        run: kind delete cluster
